### ISSUE TITLE
点搜索答案,接收的result是空数组

### ISSUE THREAD

**Issue by Tyrone2333** [CodFrm/cxmooc-tools#5] opened 2018-04-15 04:41 UTC
请问是因为后台还没有记录这个问题的答案吗?

[{topic: "10d8742ed8089627b52ebcb914934711", result: []},…]
0:{topic: "10d8742ed8089627b52ebcb914934711", result: []}
1:{topic: "e7db698fa14c8416e638759f5a71416d", result: []}
2:{topic: "3ec51b0ddf19c3cc45553758b71d3afe", result: []}

**Comment by CodFrm** [comment] 2018-04-16 11:13
Duplicate of #7

**Closed** 2018-04-16 11:14 UTC
Labels: duplicate
